#!/bin/sh -e

apk --update add $@ && rm -rf /var/cache/apk/*

strip --strip-unneeded --strip-debug /usr/lib/*.a || true

if which python &> /dev/null; then
  python -m compileall /usr/lib/python2* || true
  find /usr/lib/python2* -name '*.py' -print -delete
fi
