#!/bin/bash -e

if [ "$(which `basename $0`)" = "$0" ]; then
  echo "Installing ipython3 ..."
  min-apk jg-ipython3

  # TODO: temporary patch until fixed upstream https://github.com/ipython/ipywidgets/pull/713
  sed -i 's/new_notification_widget/widget/' /usr/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
fi

hash -r
$(basename $0) $@
