#!/bin/bash -e

if [ "$(which `basename $0`)" = "$0" ]; then
  echo "Installing Cling C++ kernel ..."
  min-apk gallery-cpp-kernel
fi

hash -r
if [ "$(which `basename $0`)" = "$0" ]; then
  echo "Installation failed!"
  exit
fi

$(basename $0) $@
