#!/bin/bash -e

if [ "$(which `basename $0`)" = "$0" ]; then
  echo "Installing IRkernel ..."
  min-apk gallery-R-kernel
fi

hash -r
if [ "$(which `basename $0`)" = "$0" ]; then
  echo "Installation failed!"
  exit
fi

$(basename $0) $@
